### ISSUE TITLE
删除非安全公众号

### ISSUE THREAD

**Issue by firmianay** [zhengjim/Chinese-Security-RSS#3]
感谢师傅整理，但是能否删掉非安全的公众号，会影响信息流，比如“从零开始定投日记”“卢瑟经济学之安生杂谈”等。

https://github.com/VulnTotal-Team/yarb/blob/main/archive/2022/2022-07-11.md

**Comment by zhengjim** [comment]
好，之前排除了一批，近期会重新排除下。

**Comment by root19890123** [comment]
！！！！！
